# Generated by Django 2.2.6 on 2019-10-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField()),
                ('relationships', models.IntegerField()),
                ('environment', models.IntegerField()),
                ('vocation', models.IntegerField()),
                ('prosperity', models.IntegerField()),
                ('selfImprovement', models.IntegerField()),
                ('brightnessOfLife', models.IntegerField()),
                ('spirituality', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel', to='wheel.Author')),
            ],
        ),
    ]
