# Generated by Django 2.2.6 on 2019-10-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0003_auto_20191026_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoBrightnessOfLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDo', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDo', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDo', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoProsperity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDo', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoRelationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDo', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoSelfImprovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDo', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoSpirituality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDo', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoVocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDo', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='subparagraphsbrightnessoflife',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subparagraphsenvironment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subparagraphshealth',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subparagraphsprosperity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subparagraphsrelationships',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subparagraphsselfimprovement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subparagraphsspirituality',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subparagraphsvocation',
            name='category',
        ),
        migrations.DeleteModel(
            name='BrightnessOfLife',
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Health',
        ),
        migrations.DeleteModel(
            name='Prosperity',
        ),
        migrations.DeleteModel(
            name='Relationships',
        ),
        migrations.DeleteModel(
            name='SelfImprovement',
        ),
        migrations.DeleteModel(
            name='Spirituality',
        ),
        migrations.DeleteModel(
            name='SubparagraphsBrightnessOfLife',
        ),
        migrations.DeleteModel(
            name='SubparagraphsEnvironment',
        ),
        migrations.DeleteModel(
            name='SubParagraphsHealth',
        ),
        migrations.DeleteModel(
            name='SubparagraphsProsperity',
        ),
        migrations.DeleteModel(
            name='SubParagraphsRelationships',
        ),
        migrations.DeleteModel(
            name='SubparagraphsSelfImprovement',
        ),
        migrations.DeleteModel(
            name='SubparagraphsSpirituality',
        ),
        migrations.DeleteModel(
            name='SubparagraphsVocation',
        ),
        migrations.DeleteModel(
            name='Vocation',
        ),
    ]
