# Generated by Django 2.2.6 on 2019-10-27 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0004_auto_20191026_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='todohealth',
            name='timePub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
