# Generated by Django 2.2.6 on 2019-10-27 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0005_todohealth_timepub'),
    ]

    operations = [
        migrations.AddField(
            model_name='todohealth',
            name='timeEnd',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 27, 1, 47, 37, 804886, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todohealth',
            name='timePub',
            field=models.DateTimeField(blank=True),
        ),
    ]
