# Generated by Django 2.2.6 on 2019-10-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0006_auto_20191027_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todohealth',
            name='timeEnd',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='todohealth',
            name='timePub',
            field=models.IntegerField(blank=True),
        ),
    ]
