# Generated by Django 2.2.6 on 2019-10-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0007_auto_20191027_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='todobrightnessoflife',
            name='timeEnd',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todobrightnessoflife',
            name='timePub',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoenvironment',
            name='timeEnd',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoenvironment',
            name='timePub',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoprosperity',
            name='timeEnd',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoprosperity',
            name='timePub',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todorelationships',
            name='timeEnd',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todorelationships',
            name='timePub',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoselfimprovement',
            name='timeEnd',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoselfimprovement',
            name='timePub',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todospirituality',
            name='timeEnd',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todospirituality',
            name='timePub',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todovocation',
            name='timeEnd',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todovocation',
            name='timePub',
            field=models.IntegerField(blank=True, default=1572141075),
            preserve_default=False,
        ),
    ]
